using JetBrains.Annotations;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerMovement : MonoBehaviour
{
    public float speed = 5f;
    public float runSpeed = 10f;
    public float jumpForce = 10f;
    private int jumpsLeft = 2;

    private Rigidbody2D rb;
    private AudioSource audioSource;
    public AudioClip jumpClip;


    void Start()
    {
        rb = GetComponent<Rigidbody2D>();
        audioSource = GetComponent<AudioSource>();
    }

    void Update()
    {
        float moveInput = Input.GetAxis("Horizontal");

        // Correr al presionar LeftShift
        if (Input.GetKey(KeyCode.LeftShift))
        {
            rb.velocity = new Vector2(moveInput * runSpeed, rb.velocity.y);
        }
        else
        {
            rb.velocity = new Vector2(moveInput * speed, rb.velocity.y);
        }

        // Saltar solo si quedan saltos disponibles
        if (jumpsLeft > 0 && Input.GetKeyDown(KeyCode.Space))
        {
            audioSource.PlayOneShot(jumpClip);
            rb.velocity = new Vector2(rb.velocity.x, jumpForce);
            jumpsLeft--;
        }
    }

    void OnCollisionEnter2D(Collision2D collision)
    {
        // Restablecer la cantidad de saltos al tocar el suelo
        jumpsLeft = 2;
    }
}
